services:
  postgres-notifications:
    image: postgres:16
    environment:
      POSTGRES_DB: notifications
      POSTGRES_USER: notifications_user
      POSTGRES_PASSWORD: notifications_pass
    ports:
      - "5437:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
